---

- name: 'Downloading Harbor'
  get_url:
      url: https://github.com/goharbor/harbor/releases/download/v{{ harbor_version }}-rc1/harbor-offline-installer-v{{ harbor_version }}-rc1.tgz
      dest: /opt
      mode: '0777'
  register: harborinstall
  changed_when: no

- name: Unzip Habor File
  unarchive:
      src: /opt/harbor-offline-installer-v{{ harbor_version }}-rc1.tgz
      dest: /opt
      remote_src: yes

- name: Copy Habor Configuration
  template:
      src: harbor.yml
      dest: /opt/harbor
      backup: yes
      
- name: Install Harbor
  shell: /opt/harbor/install.sh {{ harbor_install_args }}